import type { Metadata } from 'next'

export const locales = ['fr', 'en'] as const
export type Locale = (typeof locales)[number]
export const defaultLocale: Locale = 'fr'

export const SITE_URL = 'https://www.wescaleup.tech'

const ogLocales: Record<Locale, string> = {
  fr: 'fr_FR',
  en: 'en_US',
}

export function isLocale(value: string): value is Locale {
  return (locales as readonly string[]).includes(value)
}

/** Pages that exist with the same slug in every language (paths without the language prefix). */
export const sharedRoutes = [
  '/',
  '/services',
  '/services/meta-ads',
  '/services/sea',
  '/services/seo',
  '/services/analytics',
  '/services/automation',
  '/services/custom-saas',
  '/contact',
]

/** Pages whose slug differs between languages (paths without the language prefix). */
export const localizedSlugs: Record<Locale, string>[] = [
  { fr: '/confidentialite', en: '/privacy' },
  { fr: '/mentions-legales', en: '/terms' },
]

/** Metadata routes generated by Next.js inside each language (share images). */
const metadataRoutes = ['/opengraph-image', '/twitter-image']

/** True if `path` (without language prefix) is an existing page in `lang`. */
export function isKnownPath(path: string, lang: Locale): boolean {
  return (
    sharedRoutes.includes(path) ||
    localizedSlugs.some((slugs) => slugs[lang] === path) ||
    metadataRoutes.includes(path)
  )
}

/** Converts a path (without language prefix) from one language to the other. */
export function translatePath(path: string, from: Locale, to: Locale): string {
  const match = localizedSlugs.find((entry) => entry[from] === path)
  return match ? match[to] : path
}

/** Builds an internal link with the language prefix: ('fr', '/contact') → '/fr/contact'. */
export function localizedHref(lang: Locale, path: string): string {
  if (path === '/' || path === '') return `/${lang}`
  if (path.startsWith('/#')) return `/${lang}${path.slice(1)}`
  return `/${lang}${path}`
}

export function absoluteUrl(lang: Locale, path: string): string {
  return `${SITE_URL}${localizedHref(lang, path)}`
}

/** canonical + hreflang (fr, en, x-default → fr) for a page. `path` is the path in `lang`. */
export function buildAlternates(lang: Locale, path: string): Metadata['alternates'] {
  const frPath = translatePath(path, lang, 'fr')
  const enPath = translatePath(path, lang, 'en')
  return {
    canonical: absoluteUrl(lang, path),
    languages: {
      fr: absoluteUrl('fr', frPath),
      en: absoluteUrl('en', enPath),
      'x-default': absoluteUrl('fr', frPath),
    },
  }
}

interface PageMetadataInput {
  lang: Locale
  /** Path without the language prefix, e.g. '/services/seo' */
  path: string
  title: string
  description: string
  /** Use the title as-is (no "| Wescaleup" suffix) — for the home page */
  absoluteTitle?: boolean
  ogTitle?: string
  ogDescription?: string
  twitterDescription?: string
}

export function pageMetadata({
  lang,
  path,
  title,
  description,
  absoluteTitle = false,
  ogTitle,
  ogDescription,
  twitterDescription,
}: PageMetadataInput): Metadata {
  const fullTitle = absoluteTitle ? title : `${title} | Wescaleup`
  const shareTitle = ogTitle ?? fullTitle
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: buildAlternates(lang, path),
    openGraph: {
      type: 'website',
      locale: ogLocales[lang],
      alternateLocale: locales.filter((l) => l !== lang).map((l) => ogLocales[l]),
      url: absoluteUrl(lang, path),
      siteName: 'Wescaleup',
      title: shareTitle,
      description: ogDescription ?? description,
      // Share image generated by app/[lang]/opengraph-image.tsx (declared here because
      // a page-level openGraph object replaces the one inherited from the layout)
      images: [{ url: `/${lang}/opengraph-image`, width: 1200, height: 630, alt: 'Wescaleup' }],
    },
    twitter: {
      card: 'summary_large_image',
      title: shareTitle,
      description: twitterDescription ?? ogDescription ?? description,
      images: [`/${lang}/twitter-image`],
    },
  }
}
